version: '3.8'

services:
  app:
    container_name: eco-commerce-gs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
